### ISSUE TITLE
显示与邮件通知

### ISSUE THREAD

**Issue by ShaoyuWang1** [leirock/hexo-next-artalk#11]
1. Artalk 在本地可以显示但在服务器上无法显示
2. Artalk 评论区在本地可以显示，但配置过qq smtp和ali dm之后均无法实现邮件通知，不知如何解决？

**Comment by ShaoyuWang1** [comment]
服务器上：
<img width="1330" alt="image" src="https://github.com/leirock/hexo-next-artalk/assets/40138256/6900f288-f8e4-4638-bedb-c5f2d1aa3e2e">
本地：
<img width="1515" alt="image" src="https://github.com/leirock/hexo-next-artalk/assets/40138256/6b8797eb-077f-4e43-97f9-ebc339a39a78">

**Comment by ShaoyuWang1** [comment]
可信域名也已经设置：
<img width="1749" alt="image" src="https://github.com/leirock/hexo-next-artalk/assets/40138256/51f9f035-72ec-4abe-8bc9-dfb6d629610a">

**Comment by leirock** [comment]
可以参考我在 Artalk 项目 Issue 中的回答，检查一下是不是 Hexo 关于 Artalk 的设置存在缺失。https://github.com/ArtalkJS/Artalk/issues/763#issuecomment-1925582233

另外可以参考我博客的 [相关配置](https://github.com/leirock/blog/blob/1a04dbb0896166b05f5387872caef9f2d56738fa/_config.yml#L139-L148)。

关于邮件通知，这个插件不负责实现，是 Artalk 后端负责的，你可以向 [Artalk](https://github.com/ArtalkJS/Artalk) 开发者咨询。

**Comment by ShaoyuWang1** [comment]
原来插件是您开发的哈哈，刚注意到 感谢！我已经成功解决，帖子很有帮助，不过我的实际原因是我用https 访问http的artalk server，在全都设置为https以及设置对应证书后问题解决
