### ISSUE TITLE
next主题主页能不能关掉artalk啊

### ISSUE THREAD

**Issue by LeenHawk** [leirock/hexo-next-artalk#6]

**Comment by leirock** [comment]
如果是因为首页目前无法加载评论数和浏览数的问题，那么这个应该是因为新版 Artalk 与插件不兼容的问题，还在和 Artalk 开发者沟通解决这个 bug。 https://github.com/ArtalkJS/Artalk/issues/462

如果只是想关掉首页的 Artalk 相关评论数和浏览数显示，我印象中插件没有开发相关的功能，暂时没有增加的计划，不过欢迎您的 PR。

**Comment by LeenHawk** [comment]
> 如果是因为首页目前无法加载评论数和浏览数的问题，那么这个应该是因为新版 Artalk 与插件不兼容的问题，还在和 Artalk 开发者沟通解决这个 bug。
> 
> 如果只是想关掉首页的 Artalk 相关评论数和浏览数显示，我印象中插件没有开发相关的功能，暂时没有增加的计划，不过欢迎您的 PR。

应该就是第一个问题了，主要是首页报不能加载😂

**Comment by leirock** [comment]
@LeenHawk 到时候解决了我再通知你吧，我现在的博客首页也暂时无法加载，这个 issue 先开着好了。

**Comment by leirock** [comment]
已修复，见 PR https://github.com/leirock/hexo-next-artalk/pull/7

**Comment by LeenHawk** [comment]
> @LeenHawk 到时候解决了我再通知你吧，我现在的博客首页也暂时无法加载，这个 issue 先开着好了。

评论数正常了，但是阅读人数好像炸了🥲

**Comment by LeenHawk** [comment]
> 已修复，见 PR #7

啊，只是加载太慢了
